"""Added a foreignkey and a realtionship between message and users

Revision ID: 5cbbb95f6b62
Revises: 5cbb6b3ca908
Create Date: 2026-04-14 19:00:40.944069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbbb95f6b62'
down_revision: Union[str, Sequence[str], None] = '5cbb6b3ca908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'senders', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'senders', type_='foreignkey')
    op.drop_column('senders', 'user_id')
    # ### end Alembic commands ###
