"""description of changes

Revision ID: dabc65d5c4ec
Revises: 0d878899b11d
Create Date: 2026-05-10 22:39:16.629582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabc65d5c4ec'
down_revision: Union[str, Sequence[str], None] = '0d878899b11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senders', sa.Column('ip_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senders', 'ip_address')
    # ### end Alembic commands ###
